name: Deploy to Live Channel

on:
  push:
    branches: [prod]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: https://beertechgroup.net
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
      - name: Install and build
        uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "npm"
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Run Build
        uses: borales/actions-yarn@v4
        with:
          cmd: build
      - name: Deploy on Live Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_BEER_TECH_GROUP }}"
          projectId: beer-tech-group
          channelId: live
