name: Deploy to Stage Channel

on:
  push:
    branches: [ stage ]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    environment:
      name: stage
      url: ${{ steps.deploy_on_firebase.outputs.details_url }}
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
      - name: Install and build
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
      - name: Run install
        uses: borales/actions-yarn@v4
        with:
          cmd: install
      - name: Run Build
        uses: borales/actions-yarn@v4
        with:
          cmd: build
      - name: Change node version
        uses: actions/setup-node@v3
        with:
          node-version: '18.x'
          cache: 'npm'
      - name: Deploy on Stage Firebase
        id: deploy_on_firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_BEER_TECH_GROUP }}"
          expires: 12h
          channelId: stage
          projectId: beer-tech-group