name: Deploy to Preview Channel

on:
  pull_request:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  checks: write

jobs:
  build_and_preview:
    runs-on: ubuntu-latest
    environment:
      name: development
      url: ${{ steps.deploy_on_firebase.outputs.details_url }}
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
      - name: Install and build
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - name: Deploy preview on Firebase
        id: deploy_on_firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_BEER_TECH_GROUP }}"
          expires: 1h
          projectId: beer-tech-group