name: Deploy to Preview Channel

on:
  push:
    branches: [ stage ]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v3
      - name: Install and build
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
          cache: 'npm'
      - run: npm ci
      - run: npm run build
      - name: Deploy on Stage Firebase
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_BEER_TECH_GROUP }}"
          expires: 1d
          channelId: beta
          projectId: beer-tech-group